# Generated by Django 2.2.1 on 2019-10-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_course_degreecourse_pricepolicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='table_name',
            new_name='content_type',
        ),
    ]
